import { snName } from "./conf"

const text={
    mg: {
        signin:"Miditra",
        user: "Anarana",
        mdp: "Teny miafina",
        login:"Hiditra",
        notHaveAccount:"Mbola tsy manana kaonty? Mamorona iray",
        registerMC:"Misoratra anarana",
        mdpcnf:"Manamafy teny miafina",
        register:"Hisoratra",
        haveAccount:"Efa manana kaonty? Manamarina ny tenanao",
        instantConnect:`Miaraka amin'ny ${snName}, mifandraisa avy hatrany amin'ireo olona akaiky anao`,
        settings:"Tefy",
        chngmdp:"Hisolo teny miafina",
        chngpdp:"Hisolo sary",
        deconnexion:"Te hivoaka tokoa ve ianao?",
        yes:"Eny",
        no:"Tsia",
        curMdp: "Teny miafina ankehitriny",
        newMdp: "Teny miafina vaovao",
        confNewMdp: "Manamafy teny miafina vaovao",
        ltMnAgo:"Nisera vao teo",
        aMnAgo: "Nisera iray minitra lasa izay",
        MnAgoFirst: "Nisera ",
        MnAgoSecond: " minitra lasa izay",
        aHrAgo: "Nisera iray ora lasa izay",
        HrAgoFirst: "Nisera ",
        HrAgoSecond:" ora lasa izay",
        mtad: "Nisera mihoatra ny iray andro lasa izay",
        hidepassword: "Hanafina ny teny miafina",
        showpassword: "Hampiseho ny teny miafina",
        mdpminlength: "Ny teny miafina dia tokony hanana litera 6 na mihoatra",
        mdpnotidentic: "Tsy mitovy ireo teny miafina nomenao",
        nameexists: "Efa misy mampiasa io anarana io",
        usernamenotfound: "Tsy hita io anarana io",
        mdpincorrect: "Diso ny teny miafina nampidirinao",
        smthngwntwrng: "Nisy olana niseho",
        mlg: "Malagasy",
        fr: "Frantsay",
        en: "Anglisy",
        titleauth: "Hiditra & Hisoratra anarana",
        titlemess: "Hafatra",
        messlist: "Lisitr'ireo hafatra",
        includingyou: "ahitana anao",
        you: "ianao",
        users: "Ireo mpampiasa",
        messages: "Ireo hafatra",
        lookforuser: "Hitady mpampiasa",
        sendmessage: "Handefa hafatra ...",
        makepost: "Hanely zavatra ...",
        post: "Hanely",
        save: "Hitahiry",
        success: "Tanteraka soa aman-tsara",

    },
    fr: {
        signin:"Se connecter",
        user:"Nom d'utilisateur",
        mdp:"Mot de passe",
        login:"Se connecter",
        notHaveAccount:"Vous n'avez pas encore de compte? Rejoignez-nous",
        registerMC:"S'inscrire",
        mdpcnf:"Confirmer mot de passe",
        register:"S'inscrire",
        haveAccount:"Vous avez déjà un compte? Authentifiez-vous",
        instantConnect:`Avec ${snName}, contactez instantanément tous vos proches`,
        settings:"Paramètres",
        chngmdp:"Changer le mot de passe",
        chngpdp:"Changer la photo de profil",
        deconnexion:"Voulez-vous vous déconnecter?",
        yes:"Oui",
        no:"Non",
        curMdp: "Mot de passe actuel",
        newMdp: "Nouveau mot de passe",
        confNewMdp: "Confirmer nouveau mot de passe",
        ltMnAgo:"En ligne il y a moins d'une minute",
        aMnAgo: "En ligne il y a une minute",
        MnAgoFirst: "En ligne il y a ",
        MnAgoSecond: " minutes",
        aHrAgo: "En ligne il y a une heure",
        HrAgoFirst: "En ligne il y a ",
        HrAgoSecond:" heures",
        mtad: "Actif il y a au moins un jour",
        hidepassword: "Masquer le mot de passe",
        showpassword: "Afficher le mot de passe",
        mdpminlength: "le mot de passe doit contenir 6 caractères ou plus",
        mdpnotidentic: "Les mpts de passe ne sont pas identiques",
        nameexists: "Ce nom d'utilisateur est déjà utilisé",
        usernamenotfound: "Le nom d'utilisateur est introuvable",
        mdpincorrect: "Le mot de passe saisi est incorrect",
        smthngwntwrng: "Un problème s'est produit",
        mlg: "Malagasy",
        fr: "Français",
        en: "Anglais",
        titleauth: "Se connecter & s'inscrire",
        titlemess: "Messages",
        messlist: "Liste des messages",
        includingyou: "dont vous",
        you: "vous",
        users: "Utilisateurs",
        messages: "Messages",
        lookforuser: "Rechercher un utilisateur",
        sendmessage: "Envoyer un message ...",
        makepost: "Publier quelque chose ...",
        post: "Publier",
        save: "Sauvegarder",
        success: "Succès",
        typing: "En train d'écrire ...",

    },
    en: {
        signin:"Sign in",
        user:"Username",
        mdp:"Password",
        login:"Login",
        notHaveAccount:"Do not have an account yet? Join us",
        registerMC:"Register",
        mdpcnf:"Confirm password",
        register:"Register",
        haveAccount:"Already have an account? Log in",
        instantConnect:`With ${snName}, instantly contact all your loved ones`,
        settings:"Settings",
        chngmdp:"Change password",
        chngpdp:"Change profile picture",
        deconnexion:"Do you want to disconnect?",
        yes:"Yes",
        no:"No",
        curMdp: "Current password",
        newMdp: "New password",
        confNewMdp: "Confirm new password",
        ltMnAgo:"Active less than a minute ago",
        aMnAgo: "Active a minute ago",
        MnAgoFirst: "Active ",
        MnAgoSecond: " minutes ago",
        aHrAgo: "Active an hour ago",
        HrAgoFirst: "Active ",
        HrAgoSecond:" hours ago",
        mtad: "Active more than a day ago",
        hidepassword: "Hide password",
        showpassword: "Show password",
        mdpminlength: "the password must contain 6 characters or more",
        mdpnotidentic: "Passwords are not identical",
        nameexists: "This username is already in use",
        usernamenotfound: "The user name cannot be found",
        mdpincorrect: "Incorrect password",
        smthngwntwrng: "Something went wrong",
        mlg: "Malagasy",
        fr: "French",
        en: "English",
        titleauth: "Login & Register",
        titlemess: "Messages",
        messlist: "Messages list",
        includingyou: "including you",
        you: "you",
        users: "Users",
        messages: "Messages",
        lookforuser: "Find a user",
        sendmessage: "Send a message ...",
        makepost: "Post something ...",
        post: "Post",
        save: "Save",
        success: "Success",
        typing: "Writing ...",

    }

}

const getText = lang => { return text[lang] }

export default getText